### ISSUE TITLE
hide email add of aff

### ISSUE THREAD

**Issue by karnanishikha** [anujtenani/goaffpro#174]
is it possible to hide the email addresses of the affiliates in the Network Explorer for the privacy point of view. In the Multi Level, we just want to show the names of the affiliates.

From:Urban Bag Daily
Store ID:150388
Platform:wix

**Comment by anujtenani** [comment]
Can use the following CSS (add in Look & feel -> Affiliate dashboard tab -> custom css code option)

```css
.direct_referral_email{
 display: none !important;
}
.downline_email{
 display: none !important;
}
```
